[versions]
solon = "3.10.5-SNAPSHOT"
shadow = "8.3.6"
jline = "3.30.9"
lombok = "1.18.44"

[libraries]
solon-parent = { module = "org.noear:solon-parent", version.ref = "solon" }
solon-ai-harness = { module = "org.noear:solon-ai-harness" }
solon-ai-acp = { module = "org.noear:solon-ai-acp" }
solon-ai-skill-memory = { module = "org.noear:solon-ai-skill-memory" }
solon-scheduling-simple = { module = "org.noear:solon-scheduling-simple" }
solon-server-smarthttp = { module = "org.noear:solon-server-smarthttp" }
solon-view-thymeleaf = { module = "org.noear:solon-view-thymeleaf" }
solon-web-staticfiles = { module = "org.noear:solon-web-staticfiles" }
solon-web-sse = { module = "org.noear:solon-web-sse" }
solon-logging-logback = { module = "org.noear:solon-logging-logback" }
solon-web-cors = { module = "org.noear:solon-web-cors" }
solon-test = { module = "org.noear:solon-test" }
jansi = { module = "org.fusesource.jansi:jansi" }
jline = { module = "org.jline:jline", version.ref = "jline" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
